---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/people":
    post:
      summary: create person
      tags:
      - Person
      parameters: []
      responses:
        '422':
          description: invalid params
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                taxpayer_number:
                  type: string
                cns:
                  type: string
                birthdate:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                contacts_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      number:
                        type: string
                  required:
                  - number
                addresses_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      address:
                        type: string
                      number:
                        type: string
                      district:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      zip:
                        type: string
                      addon:
                        type: string
                      ibge:
                        type: string
                  required:
                  - address
                  - number
                  - district
                  - city
                  - state
                  - zip
                  - addon
                  - ibge
              required:
              - name
              - taxpayer_number
              - cns
              - birthdate
              - email
  "/v1/people/{id}":
    get:
      summary: show person
      tags:
      - Person
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '404':
          description: not found
        '200':
          description: successful
    put:
      summary: update person
      tags:
      - Person
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '404':
          description: not found
        '422':
          description: invalid params
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: false
                status:
                  type: number
                  required: false
                contacts_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      number:
                        type: string
                        required: true
                  required:
                  - number
                addresses_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      address:
                        type: string
                        required: true
                      number:
                        type: string
                        required: true
                      district:
                        type: string
                        required: true
                      city:
                        type: string
                        required: true
                      state:
                        type: string
                        required: true
                      addon:
                        type: string
                        required: true
                      ibge:
                        type: string
                        required: true
                      zip:
                        type: string
                        required: true
                  required:
                  - address
                  - number
                  - district
                  - city
                  - state
                  - zip
                  - addon
                  - ibge
  "/v1/people/search":
    get:
      summary: search people
      tags:
      - People
      parameters:
      - name: query
        in: header
        description: query string
        schema:
          type: string
      - name: page
        in: header
        description: current page
        schema:
          type: number
      - name: per_page
        in: header
        description: count of record per page
        schema:
          type: number
      responses:
        '200':
          description: successful
        '422':
          description: failure
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
