# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  REDIS_URL: 'redis://redis:6379'
  MEILISEARCH_ACCESS_KEY: 'vU8QQBiMCakitq-XSJDOIaf9gLmpvedxAW1k79Nx0Mg'
  MEILISEARCH_URL: 'http://meilisearch:7700/'
  TWILIO_SID: 'ACd25cd9540360aad0abfdebc9783df68e'
  TWILIO_TOKEN: 'df7af7bf1aa941e1ed55d59ca36e6ec5'
  TWILIO_PHONE_NUMBER_TEST: '+15005550006'
  MAILER_DOMAIN: 'ronsal.com'
  MAILER_USERNAME: 'spt.barataomix@gmail.com'
  MAILER_PWD: 'xvhi sklv vato ftdb'
test:
  REDIS_URL: 'redis://redis:6379'
  MEILISEARCH_ACCESS_KEY: 'vU8QQBiMCakitq-XSJDOIaf9gLmpvedxAW1k79Nx0Mg'
  MEILISEARCH_URL: 'http://meilisearch:7700/'
  TWILIO_SID: 'ACd25cd9540360aad0abfdebc9783df68e'
  TWILIO_TOKEN: 'df7af7bf1aa941e1ed55d59ca36e6ec5'
  TWILIO_PHONE_NUMBER_TEST: '+15005550006'
  MAILER_DOMAIN: 'ronsal.com'
  MAILER_USERNAME: 'spt.barataomix@gmail.com'
  MAILER_PWD: 'xvhi sklv vato ftdb'